# Generated by Django 4.2.2 on 2023-06-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_fourormorefields_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourormorefields',
            name='six',
            field=models.FloatField(default=4.5),
            preserve_default=False,
        ),
    ]
